name: E2E

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-e2e]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: TestInstall
        run: go test -v -timeout 5m ./... -run ^TestInstall$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestAlreadyInstalled
        run: go test -v -timeout 5m ./... -run ^TestAlreadyInstalled$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestRemoveRequiresConfirm
        run: go test -v -timeout 5m ./... -run ^TestRemoveRequiresConfirm$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestRemove
        run: go test -v -timeout 5m ./... -run ^TestRemove$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestList
        run: go test -v -timeout 5m ./... -run ^TestList$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestInfo
        run: go test -v -timeout 5m ./... -run ^TestInfo$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestSearch
        run: go test -v -timeout 5m ./... -run ^TestSearch$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestInstallNotFound
        run: go test -v -timeout 5m ./... -run ^TestInstallNotFound$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestRemoveNotInstalled
        run: go test -v -timeout 5m ./... -run ^TestRemoveNotInstalled$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestUpdateAlreadyLatest
        run: go test -v -timeout 5m ./... -run ^TestUpdateAlreadyLatest$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestUpdate
        run: go test -v -timeout 5m ./... -run ^TestUpdate$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestUpdateAll
        run: go test -v -timeout 5m ./... -run ^TestUpdateAll$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: TestInstallSpigotMC
        run: go test -v -timeout 5m ./... -run ^TestInstallSpigotMC$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
          SKPM_TEST_SPIGOT_RESOURCE: ${{ secrets.SKPM_TEST_SPIGOT_RESOURCE }}

      - name: TestPublish
        run: go test -v -timeout 10m ./... -run ^TestPublish$
        env:
          SKPM_GITHUB_TOKEN: ${{ secrets.SKPM_GITHUB_TOKEN }}
          REGISTRY_GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
